version: '3.7'
services: 
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    env_file: env_file.env
    ports:
      - '5438:5432'
    volumes:
      - ./docker-init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker-init/docker-entrypoint.sh:/usr/bin/docker-entrypoint.sh  
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 1s
      retries: 10
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: env_file.env
    command: go run ./main.go
    ports:
      - 8009:8000
    depends_on:
      postgres:
        condition: service_healthy  
    networks: 
      - default
volumes:
  data: